disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Home"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Welcome to my portfolio"

  [params.author]
  links = [ ]

["params.author"]
name = "Nicolai Jahncke Strand"
email = "Nicolai-strand@hotmail.com"
